### ISSUE TITLE
The activity doesn't run on ubuntu's Packaged Sugar 

### ISSUE THREAD

**Issue by Dimi20cen** [sugarlabs/sonic-jump-activity#9] opened 2023-03-20 18:18 UTC
I get the following logs, might be an issue with the journal and might not be related to the activity.

```1679334842.604893 ERROR dbus.connection: Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/sugar3/datastore/datastore.py", line 61, in __datastore_created_cb
    metadata = _get_data_store().get_properties(object_id, byte_arrays=True)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/carquinyol/datastore.py", line 483, in get_properties
    metadata = self._metadata_store.retrieve(uid)
  File "/usr/lib/python3/dist-packages/carquinyol/metadatastore.py", line 79, in retrieve
    metadata = metadatareader.retrieve(metadata_path, properties)
ValueError: Failed to convert metadata value to bytes

1679334842.663259 ERROR dbus.connection: Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/sugar3/datastore/datastore.py", line 66, in __datastore_updated_cb
    metadata = _get_data_store().get_properties(object_id, byte_arrays=True)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/carquinyol/datastore.py", line 483, in get_properties
    metadata = self._metadata_store.retrieve(uid)
  File "/usr/lib/python3/dist-packages/carquinyol/metadatastore.py", line 79, in retrieve
    metadata = metadatareader.retrieve(metadata_path, properties)
ValueError: Failed to convert metadata value to bytes

1679334842.664674 ERROR dbus.connection: Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/sugar3/datastore/datastore.py", line 177, in __object_updated_cb
    properties = _get_data_store().get_properties(self._object_id,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/carquinyol/datastore.py", line 483, in get_properties
    metadata = self._metadata_store.retrieve(uid)
  File "/usr/lib/python3/dist-packages/carquinyol/metadatastore.py", line 79, in retrieve
    metadata = metadatareader.retrieve(metadata_path, properties)
ValueError: Failed to convert metadata value to bytes

1679334849.910357 ERROR dbus.connection: Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/sugar3/datastore/datastore.py", line 66, in __datastore_updated_cb
    metadata = _get_data_store().get_properties(object_id, byte_arrays=True)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/carquinyol/datastore.py", line 483, in get_properties
    metadata = self._metadata_store.retrieve(uid)
  File "/usr/lib/python3/dist-packages/carquinyol/metadatastore.py", line 79, in retrieve
    metadata = metadatareader.retrieve(metadata_path, properties)
ValueError: Failed to convert metadata value to bytes

1679334849.911588 ERROR dbus.connection: Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/sugar3/datastore/datastore.py", line 177, in __object_updated_cb
    properties = _get_data_store().get_properties(self._object_id,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/carquinyol/datastore.py", line 483, in get_properties
    metadata = self._metadata_store.retrieve(uid)
  File "/usr/lib/python3/dist-packages/carquinyol/metadatastore.py", line 79, in retrieve
    metadata = metadatareader.retrieve(metadata_path, properties)
ValueError: Failed to convert metadata value to bytes

pygame 2.1.2 (SDL 2.0.20, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Normal successful completion, pid 1923913 activity_id 459763bae7be0cd04be5845b8e62db59525c0d3b```

**Comment by quozl** [comment] 2023-03-23 22:36
Yes, that's expected.  Based on the versions in your log you are using Ubuntu 22.04, which had Sugar Datastore 0.118, with a known problem since fixed in https://github.com/sugarlabs/sugar-datastore/commit/df4f45697d07a49cbdd2fcd0c90fbaebf3c539ab caused by an API change.

Upgrade the python3-carquinyol package to fix it.  We've already fixed it.

**Closed as completed by quozl** 2023-03-23 22:36 UTC
